spring.application.name=demosec

################ SERVER ################
server.port=8081
server.servlet.context-path=/springsecurity
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

################ DATABASE ################
spring.datasource.url=jdbc:mysql://localhost:3306/demospringsecurity?createDatabaseIfNotExist=true&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################ HIKARICP POOL ################
# Tester chaque connexion avant usage (évite les connexions mortes)
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000
# Durée de vie max d'une connexion : 25 min (< MySQL wait_timeout 8h)
spring.datasource.hikari.max-lifetime=1500000
# Ping keepalive toutes les 2 min pour garder les connexions vivantes
spring.datasource.hikari.keepalive-time=120000
# Timeout pour obtenir une connexion libre du pool
spring.datasource.hikari.connection-timeout=30000
# Expulsion des connexions inactives après 5 min
spring.datasource.hikari.idle-timeout=300000
# Taille du pool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10

################ JPA ################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

################ JWT ################
app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurity2026MySuperSecretKey
app.jwt.expiration-ms=3600000


################ MAIL (Gmail SMTP) ################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=israsaadaoui070@gmail.com
spring.mail.password=exsg ajtt ntnc mlib
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true