# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy JAR app to Azure Web App - medicareaipi

on:
  push:
    branches:
      - Esprit-PIDEV_SE-4SE2-2526-MedicareIAreIAbackendprod
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./Esprit-PIDEV_SE-4SE2-2526-MedicareIAreIAbackend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/Esprit-PIDEV_SE-4SE2-2526-MedicareIAreIAbackend/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_170291083432443996CDDB5F3441BE29 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7FA60908AC544C895D728C1B984E635 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA7F23DE913F4D969DF6F95BDDD30078 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medicareaipi'
          slot-name: 'Production'
          package: '*.jar'
